# Generated by Django 5.2.16 on 2026-07-29 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokers', '0001_initial'),
        ('strategies', '0002_strategy_source_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_slug', models.SlugField(max_length=80)),
                ('mt5_symbol', models.CharField(max_length=64)),
                ('timeframe', models.CharField(default='M5', max_length=8)),
                ('lot_size', models.FloatField(default=0.01)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('armed', 'Armed'), ('paused', 'Paused'), ('stopped', 'Stopped')], default='draft', max_length=16)),
                ('live_confirmed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='brokers.tradingagent')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='strategies.strategy')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
