# Generated by Django 5.2.16 on 2026-07-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='last_agent_report',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
