# Generated by Django 5.2.16 on 2026-07-29 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_deployment_last_agent_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='trading.deployment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
