# Generated by Django 5.2.16 on 2026-07-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='source_code',
            field=models.TextField(blank=True, help_text='Original source for custom strategies (optional audit).'),
        ),
    ]
