# Generated by Django 5.2.16 on 2026-07-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0002_strategy_source_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='rule_spec',
            field=models.JSONField(blank=True, default=dict, help_text='JSON rule-spec for apps.strategies.rules.runtime strategies.'),
        ),
    ]
