# Generated by Django 5.2.16 on 2026-07-29 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_slug', models.SlugField(max_length=80)),
                ('timeframe', models.CharField(default='M5', max_length=8)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('initial_balance', models.DecimalField(decimal_places=2, default=10000, max_digits=14)),
                ('spread_pct', models.FloatField(default=0.0, help_text='Total spread as fraction of price (e.g. 0.0002 = 0.02%).')),
                ('commission', models.FloatField(default=0.0, help_text='Flat commission per closed trade.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('equity_curve', models.JSONField(blank=True, default=list)),
                ('trades', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_runs', to='strategies.strategy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
