# Generated by Django 5.2.16 on 2026-07-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='htf_timeframe',
            field=models.CharField(blank=True, default='', help_text='Optional higher timeframe for multi-TF strategies (empty = none).', max_length=8),
        ),
    ]
