# Generated by Django 5.2.16 on 2026-07-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_slug', models.SlugField(max_length=80, unique=True)),
                ('dukascopy_id', models.CharField(blank=True, max_length=120)),
                ('mt5_symbol', models.CharField(blank=True, max_length=64)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['catalog_slug'],
            },
        ),
    ]
